/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CoreValue = {
  _type: "coreValue";
  title?: string;
  description?: string;
  icon?: "shield" | "target" | "barChart3";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroOverline?: string;
  heroTitleBefore?: string;
  heroSubtitle?: string;
  whoWeAreDescription?: string;
  whoWeAreTagline?: string;
  whoWeAreServicesLine?: string;
  mission?: string;
  vision?: string;
  values?: string;
  brandPersonality?: string;
  coreValues?: Array<{
    _key: string;
  } & CoreValue>;
  valuesSectionOverline?: string;
  valuesSectionTitle?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes = CoreValue | AboutPage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint | Slug;

// Source: ../247-website/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{  heroOverline,  heroTitleBefore,  heroSubtitle,  whoWeAreDescription,  whoWeAreTagline,  whoWeAreServicesLine,  mission,  vision,  values,  brandPersonality,  coreValues,  valuesSectionOverline,  valuesSectionTitle}
export type ABOUT_PAGE_QUERY_RESULT = {
  heroOverline: null;
  heroTitleBefore: null;
  heroSubtitle: null;
  whoWeAreDescription: null;
  whoWeAreTagline: null;
  whoWeAreServicesLine: null;
  mission: null;
  vision: null;
  values: null;
  brandPersonality: null;
  coreValues: null;
  valuesSectionOverline: null;
  valuesSectionTitle: null;
} | {
  heroOverline: string | null;
  heroTitleBefore: string | null;
  heroSubtitle: string | null;
  whoWeAreDescription: string | null;
  whoWeAreTagline: string | null;
  whoWeAreServicesLine: string | null;
  mission: string | null;
  vision: string | null;
  values: string | null;
  brandPersonality: string | null;
  coreValues: Array<{
    _key: string;
  } & CoreValue> | null;
  valuesSectionOverline: string | null;
  valuesSectionTitle: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_id == \"aboutPage\"][0]{\n  heroOverline,\n  heroTitleBefore,\n  heroSubtitle,\n  whoWeAreDescription,\n  whoWeAreTagline,\n  whoWeAreServicesLine,\n  mission,\n  vision,\n  values,\n  brandPersonality,\n  coreValues,\n  valuesSectionOverline,\n  valuesSectionTitle\n}": ABOUT_PAGE_QUERY_RESULT;
  }
}

